### Update port to match .env file or controller file.
### Request 1": Create a facet
POST http://localhost:4000/facets HTTP/1.1
content-type: application/json

{
    "facetCategory": "Motivations",
    "facetDesc": "Motivated by task completion: Preferring to use tech for what it enables one to accomplish.", 
    "personaName": "Unknown",
    "personaDesc": "Unknown",
    "personaImageURL": "Unknown",
    "rating": 1 
}

### Request 2": Create another artwork
POST http://localhost:4000/facets HTTP/1.1
content-type: application/json

{
    "facetCategory": "Motivations",
    "facetDesc": "Motivated by tech interest: Preferring to use tech for the sake of enjoyment.", 
    "personaName": "Unknown",
    "personaDesc": "Unknown",
    "personaImageURL": "Unknown",
    "rating": 1 
}

### Request 3": Create a Facet
POST http://localhost:4000/facets HTTP/1.1
content-type: application/json

{
    "facetCategory": "Information Processing Style",
    "facetDesc": "Comprehensive: Preferring to gather enough information to form a complete understanding before taking action.", 
    "personaName": "Unknown",
    "personaDesc": "Unknown",
    "personaImageURL": "Unknown",
    "rating": 2 
}

### Request 4": Create a Facet
POST http://localhost:4000/facets HTTP/1.1
content-type: application/json

{
    "facetCategory": "Information Processing Style",
    "facetDesc": "Selective: Preferring to gather a small amount of information, act upon the first promising option, then repeat.", 
    "personaName": "Abi",
    "personaDesc": "Unknown",
    "personaImageURL": "Unknown",
    "rating": 2
}


### Request 5": Retrieve should return the 4 artworks.
GET http://localhost:4000/facets HTTP/1.1
content-type: application/json


### Request 6": UPDATE the last one.
PUT http://localhost:4000/facets/66d9fc6aed03ddff91df1309 HTTP/1.1
content-type: application/json

{
    "facetCategory": "Information Processing Style",
    "facetDesc": "Selective: Preferring to gather a small amount of information, act upon the first promising option, then repeat.", 
    "personaName": "Tim",
    "personaDesc": "Tim learns by tinkering, but sometimes tinkers addictively and gets distracted from their task.",
    "personaImageURL": "Unknown",
    "rating": "2"
}

### Request 7": Verify that the previous update worked
GET http://localhost:4000/facets/66d9fc9ced03ddff91df130f HTTP/1.1



### Request 20": Delete for non-existent ID. 404 status code
DELETE http://localhost:4000/facets/66d9fa049237c057793bef7b HTTP/1.1
